In [1]:
# Manipulacion de datos
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", 600)

# Visualizacion
import cufflinks as cf

# Reduccion de dimensionalidad
from varclushi import VarClusHi
from sklearn.decomposition import PCA

# Escalamiento
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.feature_selection import SelectKBest, f_regression, f_classif

# Preprocesamiento
from sklearn.preprocessing import KBinsDiscretizer

In [2]:
df = pd.read_csv("../datasets/apple_feature_engineering.csv")

### EDA (Exploratory Data Analysis)

In [3]:
df.shape

(3276, 5764)

In [4]:
non_numeric_columns = df.select_dtypes(exclude=['number']).columns

In [5]:
df_clean = df.drop(columns=non_numeric_columns)

In [6]:
#df_clean.corr()

In [7]:
corr_matrix = df_clean.sample(frac=0.1).corr()
corr_matrix

Open      High       Low     Close  Adj Close  \
Open               1.000000  0.999866  0.999916  0.999704   0.999653   
High               0.999866  1.000000  0.999883  0.999882   0.999841   
Low                0.999916  0.999883  1.000000  0.999864   0.999818   
Close              0.999704  0.999882  0.999864  1.000000   0.999955   
Adj Close          0.999653  0.999841  0.999818  0.999955   1.000000   
...                     ...       ...       ...       ...        ...   
RatioHL_ma_90      0.455039  0.457805  0.454556  0.456494   0.458354   
RatioHL_min_90     0.662115  0.663767  0.661625  0.662805   0.664478   
RatioHL_max_90    -0.053631 -0.052684 -0.053968 -0.053159  -0.051273   
RatioHL_std_90     0.039329  0.041223  0.039075  0.040630   0.042597   
RatioHL_median_90  0.498477  0.500976  0.498044  0.499719   0.501402   

                     Volume     Range  Intervalo   RatioCA   RatioHL  ...  \
Open              -0.529010  0.847410   0.116316  0.085603  0.165945  ...   
High              -0.527470  0.853236   0.129025  0.095369  0.173215  ...   
Low               -0.530423  0.845170   0.126247  0.093712  0.161945  ...   
Close             -0.528949  0.849751   0.140430  0.104308  0.168117  ...   
Adj Close         -0.528559  0.849898   0.140710  0.104604  0.168674  ...   
...                     ...       ...        ...       ...       ...  ...   
RatioHL_ma_90     -0.007179  0.499735   0.117850  0.140798  0.350918  ...   
RatioHL_min_90    -0.231693  0.636813   0.113217  0.135216  0.282235  ...   
RatioHL_max_90     0.145106 -0.000915   0.012375  0.067370  0.084174  ...   
RatioHL_std_90     0.135221  0.108322   0.058201  0.106274  0.193261  ...   
RatioHL_median_90 -0.029351  0.525548   0.114743  0.129268  0.331646  ...   

                   RatioHL_std_89  RatioHL_median_89  RatioHL_t-90  \
Open                     0.054351           0.497753      0.139757   
High                     0.056307           0.500228      0.140204   
Low                      0.054053           0.497296      0.140069   
Close                    0.055652           0.498948      0.140211   
Adj Close                0.057429           0.500600      0.141323   
...                           ...                ...           ...   
RatioHL_ma_90            0.678419           0.964530      0.249021   
RatioHL_min_90           0.208627           0.820768      0.287656   
RatioHL_max_90           0.881590           0.367323      0.055566   
RatioHL_std_90           0.972949           0.521581      0.071850   
RatioHL_median_90        0.521621           0.999355      0.270949   

                   RatioHL_diff_90  RatioHL_pct_90  RatioHL_ma_90  \
Open                     -0.038007       -0.048402       0.455039   
High                     -0.034768       -0.044775       0.457805   
Low                      -0.040273       -0.050927       0.454556   
Close                    -0.037317       -0.047619       0.456494   
Adj Close                -0.038000       -0.048214       0.458354   
...                            ...             ...            ...   
RatioHL_ma_90            -0.040170       -0.032624       1.000000   
RatioHL_min_90           -0.107821       -0.107806       0.763572   
RatioHL_max_90           -0.006035        0.000792       0.483326   
RatioHL_std_90            0.034308        0.045568       0.677332   
RatioHL_median_90        -0.068734       -0.065306       0.963842   

                   RatioHL_min_90  RatioHL_max_90  RatioHL_std_90  \
Open                     0.662115       -0.053631        0.039329   
High                     0.663767       -0.052684        0.041223   
Low                      0.661625       -0.053968        0.039075   
Close                    0.662805       -0.053159        0.040630   
Adj Close                0.664478       -0.051273        0.042597   
...                           ...             ...             ...   
RatioHL_ma_90            0.763572        0.483326        0.677332   
RatioHL_min

#### Variables Nulas

In [8]:
null_values = df.isna().sum().items()

In [9]:
null_values = [ var for var, null in null_values if null>0]

In [10]:
null_values

[]

#### Valores con infinitos

In [17]:
check_inf = lambda x: isinstance(x,(int,float)) and np.isinf(x)

In [18]:
inf_counts =  df_clean.applymap(check_inf)

In [19]:
inf_values = inf_counts.sum().items()

In [20]:
inf_values = [var for var, n_inf in inf_values if n_inf > 0]

In [35]:
#inf_values

In [21]:
df = df.drop(columns=null_values+inf_values)

In [22]:
df.to_csv('../datasets/apple_feature_engineering_clean.csv', index=False)

# Escalamiento 

In [2]:
df = pd.read_csv('../datasets/apple_feature_engineering_clean.csv')`

In [3]:
X = df.set_index('Date').drop(columns=['y'])

In [4]:
minmax = MinMaxScaler()
minmax.fit(X)

MinMaxScaler()

In [5]:
standar = StandardScaler()
standar.fit(X)

StandardScaler()

In [6]:
Xmm = pd.DataFrame(minmax.transform(X), columns=X.columns)

In [7]:
Xss = pd.DataFrame(standar.transform(X), columns=X.columns)

In [8]:
df.head(2)

Date      Open      High       Low     Close  Adj Close     Volume  \
0  2010-05-13  9.400714  9.464286  9.157143  9.227143   7.842541  599712400   
1  2010-05-14  9.112857  9.160000  8.910714  9.065000   7.704731  759362800   

      Range  Intervalo   RatioCA  ...  RatioHL_std_89  RatioHL_median_89  \
0  0.307143  -0.173571  0.981536  ...        0.032156           1.019713   
1  0.249286  -0.047857  0.994748  ...        0.032153           1.019713   

   RatioHL_t-90  RatioHL_diff_90  RatioHL_pct_90  RatioHL_ma_90  \
0      1.009982         0.023559        0.023326       1.025642   
1      1.010973         0.017003        0.016818       1.025830   

   RatioHL_min_90  RatioHL_max_90  RatioHL_std_90  RatioHL_median_90  
0        1.005211         1.29611        0.032013           1.019557  
1        1.005211         1.29611        0.031975           1.019856  

[2 rows x 5674 columns]

In [9]:
Xmm.head(2)

Open      High       Low     Close  Adj Close    Volume     Range  \
0  0.006228  0.004588  0.005236  0.004240   0.003610  0.305838  0.020289   
1  0.004577  0.002842  0.003794  0.003306   0.002814  0.392332  0.015756   

   Intervalo   RatioCA   RatioHL  ...  RatioHL_std_89  RatioHL_median_89  \
0   0.400605  0.339195  0.164683  ...        0.996063           0.549009   
1   0.407897  0.422008  0.133497  ...        0.995958           0.549009   

   RatioHL_t-90  RatioHL_diff_90  RatioHL_pct_90  RatioHL_ma_90  \
0      0.019967         0.669237        0.616434       0.610200   
1      0.023361         0.654894        0.599800       0.617473   

   RatioHL_min_90  RatioHL_max_90  RatioHL_std_90  RatioHL_median_90  
0        0.095902             1.0        0.997040           0.542418  
1        0.095902             1.0        0.995686           0.557087  

[2 rows x 5672 columns]

In [10]:
Xss.head(2)

Open      High       Low     Close  Adj Close    Volume    Range  \
0 -0.925363 -0.924766 -0.929262 -0.928587  -0.909022  1.717012 -0.60519   
1 -0.931145 -0.930801 -0.934271 -0.931840  -0.911764  2.479249 -0.64365   

   Intervalo   RatioCA   RatioHL  ...  RatioHL_std_89  RatioHL_median_89  \
0  -0.180394 -1.349746  1.106822  ...        4.316105           0.318322   
1  -0.073845 -0.403565  0.638134  ...        4.315519           0.318322   

   RatioHL_t-90  RatioHL_diff_90  RatioHL_pct_90  RatioHL_ma_90  \
0     -0.817721         1.384509        1.430280       0.970964   
1     -0.741183         1.001992        1.031619       1.006988   

   RatioHL_min_90  RatioHL_max_90  RatioHL_std_90  RatioHL_median_90  
0       -0.897995        4.995821        4.293107           0.285976  
1       -0.897995        4.995821        4.285576           0.349880  

[2 rows x 5672 columns]

# Multicolinalidad

In [11]:
numeric_df = Xmm.sample(frac=0.01).select_dtypes(include=np.number)

In [12]:
vc = VarClusHi(numeric_df)

In [13]:
#vc.varclus()

In [14]:
#vc = VarClusHi(df)

# Poder Predictivo

In [73]:
#Sin Escalar
X = df.set_index('Date').drop(columns=['y'])
y = df['y']

In [25]:
# Con Escalamiento
X = Xmm
y = df['y']

In [38]:
# 1er forma
# Definiendo K con #
kb = SelectKBest(k=100, score_func=f_regression)

In [29]:
kb.fit(X,y)

SelectKBest(k=100, score_func=<function f_regression at 0x7fcad74b35e0>)

In [30]:

kb.get_feature_names_out(

array(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Open_t-1',
       'Open_ma_1', 'Open_min_1', 'Open_max_1', 'Open_median_1',
       'Open_ma_2', 'Open_min_2', 'Open_max_2', 'Open_median_2',
       'Open_ma_3', 'Open_min_3', 'Open_max_3', 'Open_median_3',
       'Open_ma_4', 'Open_min_4', 'Open_max_4', 'Open_median_4',
       'Open_ma_5', 'Open_median_5', 'Close_t-1', 'Close_ma_1',
       'Close_min_1', 'Close_max_1', 'Close_median_1', 'Close_t-2',
       'Close_ma_2', 'Close_min_2', 'Close_max_2', 'Close_median_2',
       'Close_ma_3', 'Close_min_3', 'Close_max_3', 'Close_median_3',
       'Close_ma_4', 'Close_min_4', 'Close_max_4', 'Close_median_4',
       'Close_ma_5', 'Close_min_5', 'Close_max_5', 'Close_median_5',
       'Close_ma_6', 'Close_min_6', 'Close_max_6', 'Close_median_6',
       'Close_ma_7', 'Close_median_7', 'High_t-1', 'High_ma_1',
       'High_min_1', 'High_max_1', 'High_median_1', 'High_ma_2',
       'High_min_2', 'High_max_2', 'High_median_2', 'High_ma_3',
     

In [32]:
kb.scores_

array([2.32757691e+06, 2.99485647e+06, 3.18611272e+06, ...,
       1.34079770e+01, 4.81225458e+00, 8.14863619e+02])

In [36]:
scores = pd.DataFrame(zip(X.columns, kb.scores_)).sort_values(by=1, ascending=False)
scores

0             1
732         Close_ma_1  3.840373e+06
735     Close_median_1  3.840373e+06
3                Close  3.840373e+06
733        Close_min_1  3.840373e+06
734        Close_max_1  3.840373e+06
...                ...           ...
3654  Intervalo_diff_8  2.959916e-05
4402   RatioCA_diff_22  2.375362e-05
5146    RatioHL_pct_25  1.164614e-05
4394   RatioCA_diff_21  5.724610e-06
4322   RatioCA_diff_12  2.271318e-06

[5672 rows x 2 columns]

In [37]:
scores.set_index(0).iplot()

In [47]:
# Segunda forma
# Definiendo k al final
col_best = list(scores.loc[scores[1] > 1000000,0])

In [48]:
len(col_best)

161

# PCA 

In [58]:
pca = PCA(n_components=3)
# 2, 3, 4,  10

In [59]:
pca.fit(X)

PCA(n_components=3)

In [54]:
pca.explained_variance_ratio_.cumsum()

array([0.81810299, 0.87463059])

In [60]:
pca.explained_variance_ratio_.cumsum()

array([0.81810299, 0.87463059, 0.90213049])

In [57]:
pca.explained_variance_ratio_.cumsum()

array([0.81810299, 0.87463059, 0.90213049, 0.91447031])

In [62]:
Xp = pd.DataFrame(index=X.index, data=pca.transform(X))

In [63]:
Xp

0         1         2
0    -12.424177  4.000693  5.739156
1    -12.434217  4.307446  5.174935
2    -12.437360  4.380897  5.066189
3    -12.442365  4.469004  4.982993
4    -12.448295  4.747088  4.529406
...         ...       ...       ...
3271  27.689057 -8.941122 -0.475021
3272  27.659632 -8.904856 -0.888773
3273  27.594220 -8.989544 -1.230428
3274  27.593647 -9.037545 -1.415113
3275  27.695451 -9.348371 -1.122100

[3276 rows x 3 columns]

In [65]:
Xp.iplot(kind='scatter3d', mode='markers', x=0, y=1, z=2)

In [66]:
Xp.iplot(kind='scatter', mode='markers', x=0, y=1, z=2)

In [68]:
sc = StandardScaler()
Xs = sc.fit_transform(X)

In [69]:
pca = PCA(n_components=.90)

In [70]:
pca.fit(Xs)

PCA(n_components=0.9)

In [71]:
pca.explained_variance_ratio_.cumsum()

array([0.51063513, 0.6231275 , 0.67622659, 0.71851685, 0.74517229,
       0.76388718, 0.77774612, 0.79049512, 0.80204366, 0.81235461,
       0.81909403, 0.82488368, 0.83047391, 0.83491294, 0.83916188,
       0.84312512, 0.84695974, 0.85010167, 0.85315763, 0.85588789,
       0.85848642, 0.86093381, 0.86326174, 0.86553232, 0.86768313,
       0.86964657, 0.87147014, 0.87323614, 0.87484432, 0.87640115,
       0.8778493 , 0.87916874, 0.8804354 , 0.88167691, 0.88286886,
       0.88400762, 0.8851287 , 0.88621567, 0.8872828 , 0.88833209,
       0.88937293, 0.89040146, 0.89141644, 0.89240197, 0.89336348,
       0.89431577, 0.89523841, 0.89615293, 0.89703483, 0.89790228,
       0.89875329, 0.8995951 , 0.90042208])

In [72]:
len(pca.explained_variance_ratio_.cumsum())

53

In [74]:
xmm = MinMaxScaler()
Xmm = xmm.fit_transform(X)

In [75]:
pca.fit(Xmm)

PCA(n_components=0.9)

In [76]:
pca.explained_variance_ratio_.cumsum()

array([0.81810299, 0.87463059, 0.90213049])

In [77]:
len(pca.explained_variance_ratio_.cumsum())

3

# Transformacion Entropica (WoE, IV)

In [79]:
y.describe()

count    3276.000000
mean       55.559101
std        49.885052
min         8.491429
25%        20.076518
50%        31.846250
75%        71.695000
max       182.009995
Name: y, dtype: float64

In [89]:
yc = (y > y.shift(1))*1

In [90]:
kb = SelectKBest(k='all', score_func=f_classif)

In [93]:
kb.fit(X, yc)

SelectKBest(k='all')

In [94]:
kb.get_feature_names_out(), len(kb.get_feature_names_out())

(array(['Open', 'High', 'Low', ..., 'RatioHL_max_90', 'RatioHL_std_90',
        'RatioHL_median_90'], dtype=object),
 5672)

In [95]:
pd.DataFrame(zip(X.columns, kb.scores_)).sort_values(by=1, ascending=False)

0             1
4386    RatioCA_diff_20  9.901763e+00
4387     RatioCA_pct_20  9.841778e+00
4164     Intervalo_t-81  8.607789e+00
4385       RatioCA_t-20  7.963621e+00
4363     RatioCA_pct_17  7.654492e+00
...                 ...           ...
2584         Low_pct_53  1.984472e-05
5226     RatioHL_pct_35  1.491711e-05
4536  RatioCA_median_38  8.572205e-06
1865        High_pct_53  2.239103e-06
4884      RatioCA_ma_82  7.899071e-07

[5672 rows x 2 columns]

In [96]:
variable = 'High'

In [98]:
df['y_classif'] = yc

In [101]:
df[f'C_{variable}'] = pd.cut(df[variable], bins=10)

In [108]:
aux = df[[f'C_{variable}', 'y_classif']].groupby(f'C_{variable}').agg(['count','sum'])

In [109]:
aux

y_classif     
                       count  sum
C_High                           
(8.49, 26.092]          1231  650
(26.092, 43.52]          763  398
(43.52, 60.947]          385  200
(60.947, 78.375]         111   64
(78.375, 95.802]          69   38
(95.802, 113.23]          27   18
(113.23, 130.657]        153   81
(130.657, 148.085]       206  117
(148.085, 165.512]       203   99
(165.512, 182.94]        128   54

# Aplicacion del algoritmo WoE y IV

In [111]:
aux['evento'] = aux['y_classif','sum']

In [112]:
aux['no_evento'] = aux['y_classif','count'] - aux['y_classif','sum']

In [113]:
aux['%evento'] = aux['evento'] / aux['evento'].sum()
aux['%no_evento'] = aux['no_evento'] / aux['no_evento'].sum()

In [114]:
aux['WoE'] = np.log(aux['no_evento']/aux['%evento'])

In [115]:
aux['IV'] = (aux['%no_evento'] - aux['%evento']) * aux['WoE']

In [116]:
aux

y_classif      evento no_evento   %evento %no_evento  \
                       count  sum                                         
C_High                                                                    
(8.49, 26.092]          1231  650    650       581  0.378127   0.373154   
(26.092, 43.52]          763  398    398       365  0.231530   0.234425   
(43.52, 60.947]          385  200    200       185  0.116347   0.118818   
(60.947, 78.375]         111   64     64        47  0.037231   0.030186   
(78.375, 95.802]          69   38     38        31  0.022106   0.019910   
(95.802, 113.23]          27   18     18         9  0.010471   0.005780   
(113.23, 130.657]        153   81     81        72  0.047120   0.046243   
(130.657, 148.085]       206  117    117        89  0.068063   0.057161   
(148.085, 165.512]       203   99     99       104  0.057592   0.066795   
(165.512, 182.94]        128   54     54        74  0.031414   0.047527   

                         WoE        IV  
                                        
C_High                                  
(8.49, 26.092]      7.337276 -0.036491  
(26.092, 43.52]     7.362943  0.021317  
(43.52, 60.947]     7.371536  0.018219  
(60.947, 78.375]    7.140763 -0.050304  
(78.375, 95.802]    7.245899 -0.015910  
(95.802, 113.23]    6.756351 -0.031693  
(113.23, 130.657]   7.331715 -0.006435  
(130.657, 148.085]  7.175960 -0.078230  
(148.085, 165.512]  7.498769  0.069015  
(165.512, 182.94]   7.764579  0.125116

In [117]:
def IV(df,var,tgt):
    df[[var, tgt]].groupby(var).agg(['count','sum'])
    aux['evento'] = aux[tgt,'sum']
    aux['no_evento'] = aux[tgt,'count'] - aux[tgt,'sum']
    aux['%evento'] = aux['evento'] / aux['evento'].sum()
    aux['%no_evento'] = aux['no_evento'] / aux['no_evento'].sum()
    aux['WoE'] = np.log(aux['no_evento']/aux['%evento'])
    aux['IV'] = (aux['%no_evento'] - aux['%evento']) * aux['WoE']
    return aux['IV'].sum()

In [119]:
#recorre todas las col del DF X y discretiza cada var en intervalos 10
for variable in X.columns:
    df[f"C_{variable}"] = pd.cut(df[variable], bins=10)

In [120]:
ls_discretized = [col for col in df if col.startswith("C_")]

In [122]:
target = 'y_classif'

In [123]:
for n_bins in range(2, 10):
    for var in X.columns[:10]:
        df[f"C_{var}"] = pd.qcut(df[var], q=n_bins, duplicates="drop").cat.add_categories(["Missing"]).fillna("Missing").astype(str)
    ls_discretized = [x for x in df.columns if x.startswith("C_")]
    df_iv = pd.DataFrame(columns=["iv"])
    for var in ls_discretized:
        df_iv.loc[var, "iv"] = IV(df = df, var = var, tgt = target)
    print(f"{n_bins} bins")
    display(df_iv)

2 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

3 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

4 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

5 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

6 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

7 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

8 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

9 bins


iv
C_High               0.014604
C_Open               0.014604
C_Low                0.014604
C_Close              0.014604
C_Adj Close          0.014604
...                       ...
C_RatioHL_ma_90      0.014604
C_RatioHL_min_90     0.014604
C_RatioHL_max_90     0.014604
C_RatioHL_std_90     0.014604
C_RatioHL_median_90  0.014604

[5672 rows x 1 columns]

In [124]:
df_iv = pd.DataFrame(columns=["iv"])
for var in ls_discretized[:50]:
    df_iv.loc[var, "iv"] = IV(df = df, var = var, tgt = "y_classif")

In [125]:
df_iv.sort_values(by="iv", ascending=False)

iv
C_High           0.014604
C_Open_min_4     0.014604
C_Open_pct_3     0.014604
C_Open_ma_3      0.014604
C_Open_min_3     0.014604
C_Open_max_3     0.014604
C_Open_std_3     0.014604
C_Open_median_3  0.014604
C_Open_t-4       0.014604
C_Open_diff_4    0.014604
C_Open_pct_4     0.014604
C_Open_ma_4      0.014604
C_Open_max_4     0.014604
C_Open           0.014604
C_Open_std_4     0.014604
C_Open_median_4  0.014604
C_Open_t-5       0.014604
C_Open_diff_5    0.014604
C_Open_pct_5     0.014604
C_Open_ma_5      0.014604
C_Open_min_5     0.014604
C_Open_max_5     0.014604
C_Open_std_5     0.014604
C_Open_median_5  0.014604
C_Open_diff_3    0.014604
C_Open_t-3       0.014604
C_Open_median_2  0.014604
C_Open_std_2     0.014604
C_Low            0.014604
C_Close          0.014604
C_Adj Close      0.014604
C_Volume         0.014604
C_Range          0.014604
C_Intervalo      0.014604
C_RatioCA        0.014604
C_RatioHL        0.014604
C_Open_t-1       0.014604
C_Open_diff_1    0.014604
C_Open_pct_1     0.014604
C_Open_ma_1      0.014604
C_Open_min_1     0.014604
C_Open_max_1     0.014604
C_Open_median_1  0.014604
C_Open_t-2       0.014604
C_Open_diff_2    0.014604
C_Open_pct_2     0.014604
C_Open_ma_2      0.014604
C_Open_min_2     0.014604
C_Open_max_2     0.014604
C_Open_t-6       0.014604